import React, { useEffect, useState } from "react";
import axios from "axios";
import "../AuditLogs.css"; 

const AuditLogs = () => {
  const [logs, setLogs] = useState([]);
  const token = localStorage.getItem("token");
  useEffect(() => {
    axios
      .get("http://localhost:5000/api/audit/audit-logs", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })
      .then((res) => setLogs(res.data))
      .catch((err) => console.error(err));
  }, []);

  return (
    <div className="auditlogs-container">
      <h2 className="auditlogs-title">Audit Logs</h2>
      <div className="auditlogs-table-container">
        <table className="auditlogs-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Event</th>
              <th>Action</th>
              <th>Generated By</th>
              <th>Generated Date</th>
            </tr>
          </thead>
          <tbody>
            {logs.map((log, idx) => (
              <tr key={idx}>
                <td>{log.name}</td>
                <td>{log.event}</td>
                <td>{log.action}</td>
                <td>{log.CreatedBy_}</td>
                <td>{log.CreatedDate_}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default AuditLogs;
